import { defineConfig } from 'rolldown';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLDOWN
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig({
	input: 'src/main.ts',
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	treeshake: true,
	logLevel: 'info',
	output: {
		file: 'main.js',
		banner,
		format: 'cjs',
		sourcemap: false,
		minify: true,
	},
	transform: {
		target: 'es2018',
	},
});
